language: python
python:
# 2.5 is for centos and the old cranky people 
#  - "2.5"
#  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
# I will troubleshoot this one later
#  - "3.3"
#install: "pip install -r requirements.txt --use-mirrors"
#install:
install:
  - "pip install . --use-mirrors"
script:
### test are done in the install part ! 
 - "echo 1"
